//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DummyWeb
{


    public partial class Default
    {

        /// <summary>
        /// HeroControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DummyWeb.UserControls.Hero HeroControl;

        /// <summary>
        /// StatsRepeater control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater StatsRepeater;

        /// <summary>
        /// PlatformShowcaseControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DummyWeb.UserControls.PLatformShowcase PlatformShowcaseControl;

        /// <summary>
        /// CourseSectionControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DummyWeb.UserControls.CourseSection CourseSectionControl;

        /// <summary>
        /// SuccessStoriesControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DummyWeb.UserControls.SuccessStories SuccessStoriesControl;

        /// <summary>
        /// StudyHubControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DummyWeb.UserControls.StudyHub StudyHubControl;

        /// <summary>
        /// AnalyticsControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DummyWeb.UserControls.AnalyticsSection AnalyticsControl;

        /// <summary>
        /// FacultyControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DummyWeb.UserControls.FacultySection FacultyControl;

        /// <summary>
        /// BlogControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DummyWeb.UserControls.BlogSection BlogControl;

        /// <summary>
        /// DemoFormControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DummyWeb.UserControls.DemoForm DemoFormControl;
    }
}
